### ISSUE TITLE
[Feature Request] Add support for sending to flatpak version of telegram

### ISSUE THREAD

**Issue by Roshan-R** [AJAYK-01/telegram-desktop-nemo-action#6]
The current script does not support sending files to flatpak version of telegram.
Lot of the times, distro versions of telegram are outdated and often times, people use alternative methods to 
get a more upto date version of telegram.

**Comment by Roshan-R** [comment]
I think this may be helpfull https://phabricator.kde.org/D12896#change-GdjpVFhnKXZ4

**Comment by HariSK20** [comment]
I got it working on Flatpak and I'm now trying to combine the scripts.
